# Generated by Django 3.0.6 on 2020-05-17 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialId', models.AutoField(primary_key=True, serialize=False)),
                ('deploy', models.CharField(blank=True, max_length=40, null=True)),
                ('loss', models.FloatField(default=0)),
                ('materialName', models.CharField(blank=True, max_length=40, null=True)),
                ('preDay', models.IntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('materialInventory', models.IntegerField(default=0)),
                ('processInventory', models.IntegerField(default=0)),
                ('materialId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('deployid', models.AutoField(primary_key=True, serialize=False)),
                ('areaId', models.CharField(blank=True, max_length=40, null=True)),
                ('number', models.IntegerField(default=0)),
                ('preMatrial', models.IntegerField(default=0)),
                ('preSupplizer', models.IntegerField(default=0)),
                ('fatherId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material')),
                ('sonId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material')),
            ],
            options={
                'db_table': 'Deploy',
            },
        ),
    ]
