# Generated by Django 3.0.6 on 2020-05-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploy',
            options={'verbose_name_plural': '调配'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': '库存'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': '物料'},
        ),
        migrations.AlterField(
            model_name='deploy',
            name='areaId',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='调配区编号'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='deployid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='调配编号'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='fatherId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material', verbose_name='父物料'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='number',
            field=models.IntegerField(default=0, verbose_name='构成数'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='preMatrial',
            field=models.IntegerField(default=0, verbose_name='配料提前期'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='preSupplizer',
            field=models.IntegerField(default=0, verbose_name='供应商提前期'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='sonId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material', verbose_name='子物料'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventoryId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='库存编号'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='materialId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material', verbose_name='物料'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='materialInventory',
            field=models.IntegerField(default=0, verbose_name='工序库存'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='processInventory',
            field=models.IntegerField(default=0, verbose_name='资材库存'),
        ),
        migrations.AlterField(
            model_name='material',
            name='deploy',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='调配方式'),
        ),
        migrations.AlterField(
            model_name='material',
            name='loss',
            field=models.FloatField(default=0, verbose_name='损耗率'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='物料编号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='materialName',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='preDay',
            field=models.IntegerField(default=0, verbose_name='作业提前期'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='单位'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('productNum', models.IntegerField(default=0, verbose_name='产品数量')),
                ('ddl', models.DateField(auto_now=True, verbose_name='完工日期')),
                ('productName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Material', verbose_name='产品名称')),
            ],
            options={
                'verbose_name_plural': 'Bom记录',
                'db_table': 'Order',
            },
        ),
    ]
