# Generated by Django 3.0.6 on 2020-05-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Erp', '0005_auto_20200517_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='mrpResult',
            fields=[
                ('mrpResultId', models.AutoField(primary_key=True, serialize=False, verbose_name='结果ID')),
                ('deploy', models.CharField(blank=True, max_length=40, null=True, verbose_name='调配方式')),
                ('materialId', models.IntegerField(default=0, verbose_name='物料号')),
                ('materialName', models.CharField(blank=True, max_length=40, null=True, verbose_name='物料名称')),
                ('count', models.IntegerField(default=0, verbose_name='需求数量')),
                ('askDate', models.DateField(verbose_name='日程下达日期')),
                ('finishDate', models.DateField(verbose_name='日程完成日期')),
                ('orderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Order', verbose_name='BOM记录')),
            ],
            options={
                'verbose_name_plural': 'mrp结果',
                'db_table': 'mrpResult',
                'ordering': ['mrpResultId'],
            },
        ),
    ]
