# Generated by Django 3.0.6 on 2020-05-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Erp', '0006_mrpresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrpresult',
            options={'ordering': ['mrpResultId'], 'verbose_name_plural': 'MPS结果'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['orderId'], 'verbose_name_plural': 'MPS'},
        ),
        migrations.AlterField(
            model_name='mrpresult',
            name='orderId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Erp.Order', verbose_name='MPS编号'),
        ),
        migrations.AlterModelTable(
            name='mrpresult',
            table='MPSresult',
        ),
    ]
