# Generated by Django 3.0.6 on 2020-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Erp', '0007_auto_20200519_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrpresult',
            name='fixcount',
            field=models.IntegerField(default=0, verbose_name='花费的库存'),
        ),
    ]
